services:
  web: &web
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ${ENV_FILE:-.env}
    depends_on:
      - db
    volumes:
      - .:/app

  manage:
    <<: *web
    ports:
      - "5001:5000"
    command: sh -c "while true; do sleep 1; done"

  db:
    image: postgres:15
    restart: always
    env_file:
      - ${ENV_FILE:-.env}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
